# Generated by Django 3.0.3 on 2020-04-21 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20200410_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=100)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Review')),
                ('traveler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Traveler')),
            ],
        ),
    ]
