# Generated by Django 3.0.3 on 2020-04-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
